basic:
  filename: 'claims.csv'  # Applies only for 'harvest_dev' action
  dir_name: 'search_results'  # Applies only for 'harvest_dev' action
html:
  parser: 'html.parser'
  blacklist: ['input', 'button', 'time', 'template',
              'form', 'select', 'footer']
similarity:
  metric: 'bow'  # Choose between 'bow' and 'emb'