model:
  path: 'data/trainer_results/mlp_2021-03-31-11:39.joblib'
features: [
  's_embedding',
  's_subjectivity',
  's_subjectivity_counts',
  's_sentiment',
  's_sentiment_counts',
  's_emotion_anger',
  's_emotion_disgust',
  's_emotion_fear',
  's_emotion_happiness',
  's_emotion_sadness',
  's_emotion_surprise',
  's_pg_polarity_counts',
  'r_title_embedding',
  'r_title_similarity',
  'r_title_subjectivity',
  'r_title_subjectivity_counts',
  'r_title_sentiment',
  'r_title_sentiment_counts',
  'r_title_emotion_anger',
  'r_title_emotion_disgust',
  'r_title_emotion_fear',
  'r_title_emotion_happiness',
  'r_title_emotion_sadness',
  'r_title_emotion_surprise',
  'r_title_pg_polarity_counts',
  'r_body_embedding',
  'r_body_similarity',
  'r_body_subjectivity',
  'r_body_subjectivity_counts',
  'r_body_sentiment',
  'r_body_sentiment_counts',
  'r_body_emotion_anger',
  'r_body_emotion_disgust',
  'r_body_emotion_fear',
  'r_body_emotion_happiness',
  'r_body_emotion_sadness',
  'r_body_emotion_surprise',
  'r_body_pg_polarity_counts',
  'r_sim_par_embedding',
  'r_sim_par_similarity',
  'r_sim_par_subjectivity',
  'r_sim_par_subjectivity_counts',
  'r_sim_par_sentiment',
  'r_sim_par_sentiment_counts',
  'r_sim_par_emotion_anger',
  'r_sim_par_emotion_disgust',
  'r_sim_par_emotion_fear',
  'r_sim_par_emotion_happiness',
  'r_sim_par_emotion_sadness',
  'r_sim_par_emotion_surprise',
  'r_sim_par_pg_polarity_counts',
  'r_sim_sent_embedding',
  'r_sim_sent_similarity',
  'r_sim_sent_subjectivity',
  'r_sim_sent_subjectivity_counts',
  'r_sim_sent_sentiment',
  'r_sim_sent_sentiment_counts',
  'r_sim_sent_emotion_anger',
  'r_sim_sent_emotion_disgust',
  'r_sim_sent_emotion_fear',
  'r_sim_sent_emotion_happiness',
  'r_sim_sent_emotion_sadness',
  'r_sim_sent_emotion_surprise',
  'r_sim_sent_pg_polarity_counts'
]