classifiers: [
  {name: nb, class: GaussianNB, params: {}},
  {name: knn, class: KNeighborsClassifier, params: {
    'n_neighbors': [3, 5, 10]}},
  {name: lr, class: LogisticRegression, params: {
    'max_iter': [100, 500], 'C': [0.1, 1, 10]}},
  {name: svm, class: SVC, params: [
    {'kernel': ['rbf'], 'gamma': [0.001, 0.0001], 'C': [0.01, 0.1, 1, 10, 100]},
    {'kernel': ['poly'], 'degree': [1, 2, 3], 'C': [0.01, 0.1, 1, 10, 100]}]},
  {name: mlp, class: MLPClassifier, params: {
    'hidden_layer_sizes': [[100], [50, 50]],
    'learning_rate_init': [0.0001, 0.01, 0.1],
    'max_iter': [100, 200, 500]}},
  {name: dt, class: DecisionTreeClassifier, params: {
    'max_depth': [1, 4, 16], 'min_samples_split': [0.1, 0.5, 1.0]}},
  {name: rf, class: RandomForestClassifier, params: {
    'max_depth': [10, 100, 1000], 'n_estimators': [250, 1000]}},
  {name: et, class: ExtraTreesClassifier, params: {
    'max_depth': [10, 100, 1000], 'n_estimators': [250, 1000]}},
]
gs:
  scoring: ['accuracy', 'f1', 'precision', 'recall']
  refit: 'accuracy'
  n_splits: 5
features: [
  's_embedding',
  's_subjectivity',
  's_subjectivity_counts',
  's_sentiment',
  's_sentiment_counts',
  's_emotion_anger',
  's_emotion_disgust',
  's_emotion_fear',
  's_emotion_happiness',
  's_emotion_sadness',
  's_emotion_surprise',
  's_pg_polarity_counts',
  'r_title_embedding',
  'r_title_similarity',
  'r_title_subjectivity',
  'r_title_subjectivity_counts',
  'r_title_sentiment',
  'r_title_sentiment_counts',
  'r_title_emotion_anger',
  'r_title_emotion_disgust',
  'r_title_emotion_fear',
  'r_title_emotion_happiness',
  'r_title_emotion_sadness',
  'r_title_emotion_surprise',
  'r_title_pg_polarity_counts',
  'r_body_embedding',
  'r_body_similarity',
  'r_body_subjectivity',
  'r_body_subjectivity_counts',
  'r_body_sentiment',
  'r_body_sentiment_counts',
  'r_body_emotion_anger',
  'r_body_emotion_disgust',
  'r_body_emotion_fear',
  'r_body_emotion_happiness',
  'r_body_emotion_sadness',
  'r_body_emotion_surprise',
  'r_body_pg_polarity_counts',
  'r_sim_par_embedding',
  'r_sim_par_similarity',
  'r_sim_par_subjectivity',
  'r_sim_par_subjectivity_counts',
  'r_sim_par_sentiment',
  'r_sim_par_sentiment_counts',
  'r_sim_par_emotion_anger',
  'r_sim_par_emotion_disgust',
  'r_sim_par_emotion_fear',
  'r_sim_par_emotion_happiness',
  'r_sim_par_emotion_sadness',
  'r_sim_par_emotion_surprise',
  'r_sim_par_pg_polarity_counts',
  'r_sim_sent_embedding',
  'r_sim_sent_similarity',
  'r_sim_sent_subjectivity',
  'r_sim_sent_subjectivity_counts',
  'r_sim_sent_sentiment',
  'r_sim_sent_sentiment_counts',
  'r_sim_sent_emotion_anger',
  'r_sim_sent_emotion_disgust',
  'r_sim_sent_emotion_fear',
  'r_sim_sent_emotion_happiness',
  'r_sim_sent_emotion_sadness',
  'r_sim_sent_emotion_surprise',
  'r_sim_sent_pg_polarity_counts'
]